# fly.toml app configuration file generated for monster-hunter-rise-builder on 2025-01-05T02:10:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'monster-hunter-rise-builder'
primary_region = 'gru'

kill_signal = "SIGINT"
kill_timeout = 5

[build]
dockerfile = "Dockerfile"

[[services]]
internal_port = 8080
protocol = "tcp"


  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

