app = 'monster-hunter-rise-builder'
primary_region = 'gru'

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256  # Ajustado para o plano gratuito

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "1GB"  # Dentro do limite gratuito de 3GB